/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-19 at 15:39:06 UTC 
 * Modify at your own risk.
 */

package com.appenginecomparison.senddataendpoint.model;

/**
 * Model definition for SendData.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the senddataendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SendData extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String endUserID;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sendDataID;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String text;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEndUserID() {
    return endUserID;
  }

  /**
   * @param endUserID endUserID or {@code null} for none
   */
  public SendData setEndUserID(java.lang.String endUserID) {
    this.endUserID = endUserID;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSendDataID() {
    return sendDataID;
  }

  /**
   * @param sendDataID sendDataID or {@code null} for none
   */
  public SendData setSendDataID(java.lang.String sendDataID) {
    this.sendDataID = sendDataID;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getText() {
    return text;
  }

  /**
   * @param text text or {@code null} for none
   */
  public SendData setText(java.lang.String text) {
    this.text = text;
    return this;
  }

  @Override
  public SendData set(String fieldName, Object value) {
    return (SendData) super.set(fieldName, value);
  }

  @Override
  public SendData clone() {
    return (SendData) super.clone();
  }

}
