/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-19 at 15:37:15 UTC 
 * Modify at your own risk.
 */

package com.appenginecomparison.getdataendpoint;

/**
 * Service definition for Getdataendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GetdataendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Getdataendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the getdataendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://compscipr.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "getdataendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Getdataendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Getdataendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getgetData".
   *
   * This request holds the parameters needed by the getdataendpoint server.  After setting any
   * optional parameters, call the {@link GetgetData#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetgetData getgetData(java.lang.String id) throws java.io.IOException {
    GetgetData result = new GetgetData(id);
    initialize(result);
    return result;
  }

  public class GetgetData extends GetdataendpointRequest<com.appenginecomparison.getdataendpoint.model.GetData> {

    private static final String REST_PATH = "getdata/{id}";

    /**
     * Create a request for the method "getgetData".
     *
     * This request holds the parameters needed by the the getdataendpoint server.  After setting any
     * optional parameters, call the {@link GetgetData#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetgetData#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetgetData(java.lang.String id) {
      super(Getdataendpoint.this, "GET", REST_PATH, null, com.appenginecomparison.getdataendpoint.model.GetData.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetgetData setAlt(java.lang.String alt) {
      return (GetgetData) super.setAlt(alt);
    }

    @Override
    public GetgetData setFields(java.lang.String fields) {
      return (GetgetData) super.setFields(fields);
    }

    @Override
    public GetgetData setKey(java.lang.String key) {
      return (GetgetData) super.setKey(key);
    }

    @Override
    public GetgetData setOauthToken(java.lang.String oauthToken) {
      return (GetgetData) super.setOauthToken(oauthToken);
    }

    @Override
    public GetgetData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetgetData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetgetData setQuotaUser(java.lang.String quotaUser) {
      return (GetgetData) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetgetData setUserIp(java.lang.String userIp) {
      return (GetgetData) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetgetData setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetgetData set(String parameterName, Object value) {
      return (GetgetData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertgetData".
   *
   * This request holds the parameters needed by the getdataendpoint server.  After setting any
   * optional parameters, call the {@link InsertgetData#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.appenginecomparison.getdataendpoint.model.GetData}
   * @return the request
   */
  public InsertgetData insertgetData(com.appenginecomparison.getdataendpoint.model.GetData content) throws java.io.IOException {
    InsertgetData result = new InsertgetData(content);
    initialize(result);
    return result;
  }

  public class InsertgetData extends GetdataendpointRequest<com.appenginecomparison.getdataendpoint.model.GetData> {

    private static final String REST_PATH = "getdata";

    /**
     * Create a request for the method "insertgetData".
     *
     * This request holds the parameters needed by the the getdataendpoint server.  After setting any
     * optional parameters, call the {@link InsertgetData#execute()} method to invoke the remote
     * operation. <p> {@link InsertgetData#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.appenginecomparison.getdataendpoint.model.GetData}
     * @since 1.13
     */
    protected InsertgetData(com.appenginecomparison.getdataendpoint.model.GetData content) {
      super(Getdataendpoint.this, "POST", REST_PATH, content, com.appenginecomparison.getdataendpoint.model.GetData.class);
    }

    @Override
    public InsertgetData setAlt(java.lang.String alt) {
      return (InsertgetData) super.setAlt(alt);
    }

    @Override
    public InsertgetData setFields(java.lang.String fields) {
      return (InsertgetData) super.setFields(fields);
    }

    @Override
    public InsertgetData setKey(java.lang.String key) {
      return (InsertgetData) super.setKey(key);
    }

    @Override
    public InsertgetData setOauthToken(java.lang.String oauthToken) {
      return (InsertgetData) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertgetData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertgetData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertgetData setQuotaUser(java.lang.String quotaUser) {
      return (InsertgetData) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertgetData setUserIp(java.lang.String userIp) {
      return (InsertgetData) super.setUserIp(userIp);
    }

    @Override
    public InsertgetData set(String parameterName, Object value) {
      return (InsertgetData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listgetData".
   *
   * This request holds the parameters needed by the getdataendpoint server.  After setting any
   * optional parameters, call the {@link ListgetData#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListgetData listgetData() throws java.io.IOException {
    ListgetData result = new ListgetData();
    initialize(result);
    return result;
  }

  public class ListgetData extends GetdataendpointRequest<com.appenginecomparison.getdataendpoint.model.CollectionResponseGetData> {

    private static final String REST_PATH = "getdata";

    /**
     * Create a request for the method "listgetData".
     *
     * This request holds the parameters needed by the the getdataendpoint server.  After setting any
     * optional parameters, call the {@link ListgetData#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListgetData#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListgetData() {
      super(Getdataendpoint.this, "GET", REST_PATH, null, com.appenginecomparison.getdataendpoint.model.CollectionResponseGetData.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListgetData setAlt(java.lang.String alt) {
      return (ListgetData) super.setAlt(alt);
    }

    @Override
    public ListgetData setFields(java.lang.String fields) {
      return (ListgetData) super.setFields(fields);
    }

    @Override
    public ListgetData setKey(java.lang.String key) {
      return (ListgetData) super.setKey(key);
    }

    @Override
    public ListgetData setOauthToken(java.lang.String oauthToken) {
      return (ListgetData) super.setOauthToken(oauthToken);
    }

    @Override
    public ListgetData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListgetData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListgetData setQuotaUser(java.lang.String quotaUser) {
      return (ListgetData) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListgetData setUserIp(java.lang.String userIp) {
      return (ListgetData) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListgetData setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListgetData setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListgetData set(String parameterName, Object value) {
      return (ListgetData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removegetData".
   *
   * This request holds the parameters needed by the getdataendpoint server.  After setting any
   * optional parameters, call the {@link RemovegetData#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovegetData removegetData(java.lang.String id) throws java.io.IOException {
    RemovegetData result = new RemovegetData(id);
    initialize(result);
    return result;
  }

  public class RemovegetData extends GetdataendpointRequest<Void> {

    private static final String REST_PATH = "getdata/{id}";

    /**
     * Create a request for the method "removegetData".
     *
     * This request holds the parameters needed by the the getdataendpoint server.  After setting any
     * optional parameters, call the {@link RemovegetData#execute()} method to invoke the remote
     * operation. <p> {@link RemovegetData#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovegetData(java.lang.String id) {
      super(Getdataendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovegetData setAlt(java.lang.String alt) {
      return (RemovegetData) super.setAlt(alt);
    }

    @Override
    public RemovegetData setFields(java.lang.String fields) {
      return (RemovegetData) super.setFields(fields);
    }

    @Override
    public RemovegetData setKey(java.lang.String key) {
      return (RemovegetData) super.setKey(key);
    }

    @Override
    public RemovegetData setOauthToken(java.lang.String oauthToken) {
      return (RemovegetData) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovegetData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovegetData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovegetData setQuotaUser(java.lang.String quotaUser) {
      return (RemovegetData) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovegetData setUserIp(java.lang.String userIp) {
      return (RemovegetData) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemovegetData setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovegetData set(String parameterName, Object value) {
      return (RemovegetData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updategetData".
   *
   * This request holds the parameters needed by the getdataendpoint server.  After setting any
   * optional parameters, call the {@link UpdategetData#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.appenginecomparison.getdataendpoint.model.GetData}
   * @return the request
   */
  public UpdategetData updategetData(com.appenginecomparison.getdataendpoint.model.GetData content) throws java.io.IOException {
    UpdategetData result = new UpdategetData(content);
    initialize(result);
    return result;
  }

  public class UpdategetData extends GetdataendpointRequest<com.appenginecomparison.getdataendpoint.model.GetData> {

    private static final String REST_PATH = "getdata";

    /**
     * Create a request for the method "updategetData".
     *
     * This request holds the parameters needed by the the getdataendpoint server.  After setting any
     * optional parameters, call the {@link UpdategetData#execute()} method to invoke the remote
     * operation. <p> {@link UpdategetData#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.appenginecomparison.getdataendpoint.model.GetData}
     * @since 1.13
     */
    protected UpdategetData(com.appenginecomparison.getdataendpoint.model.GetData content) {
      super(Getdataendpoint.this, "PUT", REST_PATH, content, com.appenginecomparison.getdataendpoint.model.GetData.class);
    }

    @Override
    public UpdategetData setAlt(java.lang.String alt) {
      return (UpdategetData) super.setAlt(alt);
    }

    @Override
    public UpdategetData setFields(java.lang.String fields) {
      return (UpdategetData) super.setFields(fields);
    }

    @Override
    public UpdategetData setKey(java.lang.String key) {
      return (UpdategetData) super.setKey(key);
    }

    @Override
    public UpdategetData setOauthToken(java.lang.String oauthToken) {
      return (UpdategetData) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdategetData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdategetData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdategetData setQuotaUser(java.lang.String quotaUser) {
      return (UpdategetData) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdategetData setUserIp(java.lang.String userIp) {
      return (UpdategetData) super.setUserIp(userIp);
    }

    @Override
    public UpdategetData set(String parameterName, Object value) {
      return (UpdategetData) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Getdataendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Getdataendpoint}. */
    @Override
    public Getdataendpoint build() {
      return new Getdataendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GetdataendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGetdataendpointRequestInitializer(
        GetdataendpointRequestInitializer getdataendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(getdataendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
